-- CREATE DATABASE agendamento

CREATE TABLE espaco_fisico (
	id SERIAL PRIMARY KEY,
	descricao VARCHAR(50)
);

INSERT INTO espaco_fisico (descricao) VALUES
('SALA DE CAPACITAÇÃO PERMANENTE AGHU'),
('SALA DE VIDEOCONFERÊNCIA 1'),
('SALA DE VIDEOCONFERÊNCIA 2'),
('SALA DE VIDEOCONFERÊNCIA 3');


